### ISSUE TITLE
[DOC] explain parameters

### ISSUE THREAD

**Issue by vkhodygo** [MRC-CSO-SPHSU/simpaths_parallel#1]
@andrewbaxter439 

I'd like to know what certain parts of the bash script mean:

https://github.com/MRC-CSO-SPHSU/simpaths_parallel_r/blob/c3bac440058ab8fe65cfd9857fa68055b05fa0b6/do_full_run.sh#L2

1. Why use `seq`, parallel has its own inbuilt iterator? Also, why such a long range, `1-50` should be more than enough?
2. `-r`, `-n`, `-p`, `-s`, `-e` are self-explanatory, what about `-g` & `-f`?

**Comment by andrewbaxter439** [comment]
Hi Vlad, thanks for this. Two quick answers:
1. Ah I see that using `::: {100..5000..100}` at the end of the `parallel` call would do exactly the same. These are *starting seeds* for each of the 50 parallel runs doing 20 runs each. Run 1 starts at `100` then does `101...102...103` etc. So there are no overlapping seeds in all 1,000 runs. In reality, `{1..981..20}` would be more compact non-overlapping set of seeds. Have spaced out by 100 for simplicity of identifying starting points and so that it doesn't need changed if more runs are needed.
2. `-g false` is turn off gui:

https://github.com/matteorichiardi/labsim/blob/development_UK-multirun-v2/src/main/java/simpaths/experiment/SimPathsMultiRun.java#L58

`-f` is write to file and is added in commit [d8c26f3](https://github.com/andrewbaxter439/labsim/commit/d8c26f354a53cfc56770485074c76a4e018915a6) (but not marked for pull request to main branch yet)

**Comment by vkhodygo** [comment]
Are there any limits to the parameter values?

**Comment by andrewbaxter439** [comment]
I would presume so. These are parameters defined in Simpaths which is an externally-compiled dependency of this repo. Would it be best to document their use there? Or would it be helpful to have a short comment in this script to explain what the call is achieving?

**Comment by vkhodygo** [comment]
> Would it be best to document their use there? Or would it be helpful to have a short comment in this script to explain what the call is achieving?

Both. No one is going to sift through the Simpaths code and logic to get the lowest acceptable value for the start year. This _must_ be documented and adjusted accordingly when needed.

We also need safeguards to avoid typos since these simulations are quite costly.

**Comment by andrewbaxter439** [comment]
Brief thing:

https://github.com/MRC-CSO-SPHSU/simpaths_parallel/blob/f530eb916b2706c2ea07717ce2db3aaa7efe886d/do_full_run.sh#L20

The end year has no upper bound as far as I'm aware?

**Comment by andrewbaxter439** [comment]
https://github.com/MRC-CSO-SPHSU/simpaths_parallel/blob/f530eb916b2706c2ea07717ce2db3aaa7efe886d/do_full_run.sh#L21

I think this should set `-g false` by default as I don't think showing gui with parallel multiruns is possible/useful?

**Comment by vkhodygo** [comment]
Done in 9ed76d2a6926fa847fb963d3e8afcdcd0fd1f9af
